### ISSUE TITLE
OIL_DB_DBNAME conflict

### ISSUE THREAD

**Issue by n33tfr33k** [FanFicDev/hermes#3]
In hermes/doc/db_setup we are shown the environment variables needed for the Database:
`OIL_DB_DBNAME (defaults to hermes)`

In skitter_api/home/.config/oil.bashrc we have:
`OIL_DB_DBNAME=$(whoami)`

This may be intentional as perhaps they were never intended to run under the same user as I was doing.  But it caught my eye as I was working with skitter.

**Comment by iridescent-beacon** [comment]
Thanks for bringing this up; I can definitely see how this is confusing. Let me try to explain it here, and then I have several things I need to update across several repositories :)

The note in the `doc/db_setup` file are referring to the defaults that `hermes` and `alexandria_api` from this repository use when no environment variables are set, which come from `lite_oil.py` https://github.com/FanFicDev/hermes/blob/master/lite_oil.py#L9-L15 
```python
	connParms: Dict[str, Optional[str]] = {
		'dbname': 'hermes',  # TODO
		'user': None,
		'password': None,
		'host': None,
		'port': None,
	}
```

Meanwhile, over in the [skitter_api](https://github.com/FanFicDev/skitter_api) repository the `home/` directory exists to help me deploy to the current production skitter environment. A few things to note:
* a user wouldn't normally use anything in the `home/` directory at all
* while named the same (from having a similar providence) the `OIL_DB_*` environment variables don't have to -- and actually cannot currently -- point to the same thing
* indeed, the schema for `hermes`/`alexandria` is not the same schema as `skitter` and in production they use different databases
* the db schema that `skitter_api` uses is actually from [python-weaver](https://github.com/FanFicDev/python-weaver/blob/master/sql/weaver.sql)
* _those_ defaults come from [python-oil](https://github.com/FanFicDev/python-oil/blob/master/src/db/postgres.py#L12-L18)
* the naming here clearly needs cleaned up
* pieces are still moving around and need fully deduplicated

You _can_ run both projects as the same user, you just have to set the variables per-process so that they both talk to the correct databases. The production environment separates services by user, so I simply set the environment variables in all those users' shells.

Does that clarify things at all? I think looking at this repository in isolation the documentation reads correctly. When looking through associated projects it quickly gets jumbled, and those other projects need improved documentation.

**Comment by n33tfr33k** [comment]
Got it, thank you for explaining.  I will follow the intended production structure and divide the services by user.  Resolving.
